-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0e0a07",
    surface = "27231f",
    surface_high = "322d2a",
    foreground = "f5ece6",
    muted = "d3c4b6",
    primary = "ebbf8b",
    primary_container = "cda372",
    on_primary_container = "000000",
    secondary = "dac3aa",
    tertiary = "acc9e9",
    outline = "a6998c",
    outline_variant = "766b5f",
    shadow = "000000",
}
