-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0b0b0a",
    surface = "242322",
    surface_high = "2f2e2d",
    foreground = "f1edea",
    muted = "cac6bb",
    primary = "cbc7b4",
    primary_container = "999584",
    on_primary_container = "000000",
    secondary = "cac6bd",
    tertiary = "cdc3cf",
    outline = "9e9b91",
    outline_variant = "6f6c63",
    shadow = "000000",
}
