-- Generated by Matugen. Do not edit this output directly.
return {
    background = "050c10",
    surface = "1e2529",
    surface_high = "282f34",
    foreground = "e8eff5",
    muted = "bbc8d2",
    primary = "dec663",
    primary_container = "7e6c0e",
    on_primary_container = "ffffff",
    secondary = "d3bfe6",
    tertiary = "97ceec",
    outline = "8f9da6",
    outline_variant = "616e77",
    shadow = "000000",
}
