-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0e0a0a",
    surface = "282222",
    surface_high = "322d2d",
    foreground = "f6ebea",
    muted = "d6c2c1",
    primary = "f5b7b6",
    primary_container = "925f5f",
    on_primary_container = "ffffff",
    secondary = "dfbfbe",
    tertiary = "a5d0b9",
    outline = "a99796",
    outline_variant = "796968",
    shadow = "000000",
}
