-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0e0a0a",
    surface = "272323",
    surface_high = "322d2d",
    foreground = "f5eceb",
    muted = "d4c2c2",
    primary = "ecbabb",
    primary_container = "b28586",
    on_primary_container = "000000",
    secondary = "dbc0c0",
    tertiary = "aeceba",
    outline = "a79797",
    outline_variant = "786969",
    shadow = "000000",
}
