-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0e0a0a",
    surface = "272323",
    surface_high = "322d2d",
    foreground = "f5eceb",
    muted = "d4c2c2",
    primary = "edbaba",
    primary_container = "8c6262",
    on_primary_container = "ffffff",
    secondary = "dbc0c0",
    tertiary = "aeceb9",
    outline = "a89797",
    outline_variant = "786969",
    shadow = "000000",
}
