-- Generated by Matugen. Do not edit this output directly.
return {
    background = "090b0e",
    surface = "212427",
    surface_high = "2c2e32",
    foreground = "ededf2",
    muted = "c1c7d0",
    primary = "96ccfe",
    primary_container = "3c74a2",
    on_primary_container = "ffffff",
    secondary = "b5c9df",
    tertiary = "f4bd68",
    outline = "959ba4",
    outline_variant = "676d75",
    shadow = "000000",
}
