-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0f0a06",
    surface = "28231d",
    surface_high = "332d27",
    foreground = "f8ece3",
    muted = "d5c3b3",
    primary = "fcba6e",
    primary_container = "bf853e",
    on_primary_container = "000000",
    secondary = "e4c09c",
    tertiary = "8fcef9",
    outline = "a89889",
    outline_variant = "786a5c",
    shadow = "000000",
}
