-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0d0a09",
    surface = "272322",
    surface_high = "312d2c",
    foreground = "f5ece9",
    muted = "d4c3bd",
    primary = "e9bdac",
    primary_container = "886556",
    on_primary_container = "ffffff",
    secondary = "d9c2b9",
    tertiary = "adcdcb",
    outline = "a79892",
    outline_variant = "776a65",
    shadow = "000000",
}
