-- Generated by Matugen. Do not edit this output directly.
return {
    background = "{{colors.surface_container_lowest.dark.hex_stripped}}",
    surface = "{{colors.surface_container.dark.hex_stripped}}",
    surface_high = "{{colors.surface_container_high.dark.hex_stripped}}",
    foreground = "{{colors.on_surface.dark.hex_stripped}}",
    muted = "{{colors.on_surface_variant.dark.hex_stripped}}",
    primary = "{{colors.primary.dark.hex_stripped}}",
    primary_container = "{{colors.primary_container.dark.hex_stripped}}",
    on_primary_container = "{{colors.on_primary_container.dark.hex_stripped}}",
    secondary = "{{colors.secondary.dark.hex_stripped}}",
    tertiary = "{{colors.tertiary.dark.hex_stripped}}",
    outline = "{{colors.outline.dark.hex_stripped}}",
    outline_variant = "{{colors.outline_variant.dark.hex_stripped}}",
    shadow = "{{colors.shadow.dark.hex_stripped}}",
}
