-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0d0b07",
    surface = "26231e",
    surface_high = "312e28",
    foreground = "f4ede4",
    muted = "d0c5b4",
    primary = "e3c37c",
    primary_container = "b89b58",
    on_primary_container = "000000",
    secondary = "d6c5a3",
    tertiary = "bac4f6",
    outline = "a39a8a",
    outline_variant = "746c5d",
    shadow = "000000",
}
