-- Generated by Matugen. Do not edit this output directly.
return {
    background = "150806",
    surface = "30201d",
    surface_high = "3c2a27",
    foreground = "ffe9e6",
    muted = "e4beb8",
    primary = "ffb4a9",
    primary_container = "ce2e22",
    on_primary_container = "ffffff",
    secondary = "ffb4a9",
    tertiary = "b6c4ff",
    outline = "b6938e",
    outline_variant = "846561",
    shadow = "000000",
}
