-- Generated by Matugen. Do not edit this output directly.
return {
    background = "130905",
    surface = "2d211c",
    surface_high = "392b26",
    foreground = "ffe9e2",
    muted = "dfc0b4",
    primary = "aec6ff",
    primary_container = "4e6ca8",
    on_primary_container = "ffffff",
    secondary = "c2cb98",
    tertiary = "a6d2a0",
    outline = "b1958a",
    outline_variant = "80675d",
    shadow = "000000",
}
