-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0d0a10",
    surface = "26222a",
    surface_high = "312d34",
    foreground = "f4ebf5",
    muted = "cdc3d3",
    primary = "dab9ff",
    primary_container = "ac78eb",
    on_primary_container = "000000",
    secondary = "d5bdf0",
    tertiary = "e4c453",
    outline = "a198a7",
    outline_variant = "726a78",
    shadow = "000000",
}
