-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0b0b0b",
    surface = "242424",
    surface_high = "2e2e2e",
    foreground = "f0edec",
    muted = "c3c7c8",
    primary = "bec8c9",
    primary_container = "667071",
    on_primary_container = "ffffff",
    secondary = "c4c7c7",
    tertiary = "d8c2b9",
    outline = "979c9c",
    outline_variant = "696d6e",
    shadow = "000000",
}
