-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0f0a07",
    surface = "29221f",
    surface_high = "342d29",
    foreground = "f8ebe6",
    muted = "d8c2b8",
    primary = "ffb68f",
    primary_container = "9b5d3a",
    on_primary_container = "ffffff",
    secondary = "e7bea9",
    tertiary = "99cee5",
    outline = "aa978e",
    outline_variant = "7a6961",
    shadow = "000000",
}
