-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0d0a0a",
    surface = "262323",
    surface_high = "312d2d",
    foreground = "f4eceb",
    muted = "d3c3c2",
    primary = "e3bebd",
    primary_container = "846565",
    on_primary_container = "ffffff",
    secondary = "d6c2c1",
    tertiary = "b6ccbd",
    outline = "a69897",
    outline_variant = "776a69",
    shadow = "000000",
}
