-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0e0a0c",
    surface = "272225",
    surface_high = "322d2f",
    foreground = "f6ebee",
    muted = "d3c2c9",
    primary = "f5b3da",
    primary_container = "925b7d",
    on_primary_container = "ffffff",
    secondary = "debdcf",
    tertiary = "afd192",
    outline = "a6979e",
    outline_variant = "77696f",
    shadow = "000000",
}
