-- Generated by Matugen. Do not edit this output directly.
return {
    background = "060c09",
    surface = "1f2521",
    surface_high = "29302b",
    foreground = "e9f0e9",
    muted = "bccabf",
    primary = "59dda4",
    primary_container = "22b47e",
    on_primary_container = "000000",
    secondary = "a1d1b6",
    tertiary = "ffb3b0",
    outline = "909e95",
    outline_variant = "627067",
    shadow = "000000",
}
