-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0b0b0a",
    surface = "242422",
    surface_high = "2f2e2c",
    foreground = "f1edea",
    muted = "cac6bb",
    primary = "cbc7b4",
    primary_container = "a9a593",
    on_primary_container = "000000",
    secondary = "cac6bd",
    tertiary = "ccc4cf",
    outline = "9e9b91",
    outline_variant = "6f6d63",
    shadow = "000000",
}
