-- Generated by Matugen. Do not edit this output directly.
return {
    background = "100a06",
    surface = "2a221d",
    surface_high = "352d27",
    foreground = "faebe2",
    muted = "d8c2b4",
    primary = "ffb77f",
    primary_container = "a05c1c",
    on_primary_container = "ffffff",
    secondary = "ecbd9b",
    tertiary = "91cdff",
    outline = "ab978a",
    outline_variant = "7b695d",
    shadow = "000000",
}
