-- Generated by Matugen. Do not edit this output directly.
return {
    background = "070c0e",
    surface = "202427",
    surface_high = "2a2f32",
    foreground = "ebeef2",
    muted = "bec8cf",
    primary = "73d1ff",
    primary_container = "349fcb",
    on_primary_container = "000000",
    secondary = "a9cbdf",
    tertiary = "ffb871",
    outline = "929ca3",
    outline_variant = "646e74",
    shadow = "000000",
}
