-- Generated by Matugen. Do not edit this output directly.
return {
    background = "090b11",
    surface = "21242a",
    surface_high = "2c2e35",
    foreground = "ededf6",
    muted = "c3c6d5",
    primary = "afc6ff",
    primary_container = "306ad2",
    on_primary_container = "ffffff",
    secondary = "b4c6f5",
    tertiary = "ffb689",
    outline = "979aa9",
    outline_variant = "686c7a",
    shadow = "000000",
}
