-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0d0a08",
    surface = "272320",
    surface_high = "312d2b",
    foreground = "f5ece8",
    muted = "d3c4b9",
    primary = "e9be9c",
    primary_container = "89674a",
    on_primary_container = "ffffff",
    secondary = "d9c2b2",
    tertiary = "aaccd5",
    outline = "a6988f",
    outline_variant = "776a61",
    shadow = "000000",
}
