-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0b0b0b",
    surface = "242424",
    surface_high = "2e2e2f",
    foreground = "f0eded",
    muted = "c4c6cb",
    primary = "bfc7d1",
    primary_container = "929aa3",
    on_primary_container = "000000",
    secondary = "c5c6ca",
    tertiary = "d9c2b2",
    outline = "999b9f",
    outline_variant = "6a6d71",
    shadow = "000000",
}
