-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0a0b0d",
    surface = "232326",
    surface_high = "2e2e31",
    foreground = "efedf0",
    muted = "c6c6cf",
    primary = "b8c5f1",
    primary_container = "8390b9",
    on_primary_container = "000000",
    secondary = "c2c6d9",
    tertiary = "e2c382",
    outline = "9a9aa3",
    outline_variant = "6b6c74",
    shadow = "000000",
}
