-- Generated by Matugen. Do not edit this output directly.
return {
    background = "090b0e",
    surface = "222426",
    surface_high = "2c2e31",
    foreground = "ededf1",
    muted = "c1c7cf",
    primary = "9dcbf5",
    primary_container = "427196",
    on_primary_container = "ffffff",
    secondary = "b7c8db",
    tertiary = "fbb97c",
    outline = "969ba3",
    outline_variant = "676d74",
    shadow = "000000",
}
