-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0b0b0a",
    surface = "242423",
    surface_high = "2f2e2d",
    foreground = "f0edeb",
    muted = "c6c7bf",
    primary = "c5c8be",
    primary_container = "8f9289",
    on_primary_container = "000000",
    secondary = "c7c7c2",
    tertiary = "d1c3c6",
    outline = "9a9c94",
    outline_variant = "6b6d67",
    shadow = "000000",
}
