-- Generated by Matugen. Do not edit this output directly.
return {
    background = "10090a",
    surface = "2a2223",
    surface_high = "352c2d",
    foreground = "faeaec",
    muted = "d9c1c4",
    primary = "ffb1c2",
    primary_container = "a75167",
    on_primary_container = "ffffff",
    secondary = "eeb9c3",
    tertiary = "91d794",
    outline = "ab9699",
    outline_variant = "7b686b",
    shadow = "000000",
}
