-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0f0a05",
    surface = "29231b",
    surface_high = "342d25",
    foreground = "f9ecdf",
    muted = "d3c4b4",
    primary = "f6bc70",
    primary_container = "916320",
    on_primary_container = "ffffff",
    secondary = "dec2a2",
    tertiary = "b9cda0",
    outline = "a7998a",
    outline_variant = "776b5d",
    shadow = "000000",
}
