general {
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.02
    contrast = 0.9
    brightness = 0.65
}

label {
    monitor =
    text = cmd[update:1000] date '+%H:%M'
    color = rgba(29434aff)
    font_family = JetBrainsMono Nerd Font
    font_size = 72
    position = 0, 70
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date '+%A, %d %B'
    color = rgba(58725fff)
    font_family = JetBrainsMono Nerd Font
    font_size = 18
    position = 0, 10
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 54
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    outer_color = rgba(1f2937ff)
    inner_color = rgba(f7f0dcef)
    font_color = rgba(29434aff)
    font_family = JetBrainsMono Nerd Font
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}
