# Fixed manual theme. Managed by hypr-theme-select.
background @background@
foreground @foreground@
cursor @primary@
cursor_text_color @on_primary@
selection_background @primary_container@
selection_foreground @on_primary_container@

color0 @surface_high@
color1 @error@
color2 @primary@
color3 @secondary@
color4 @tertiary@
color5 @primary_container@
color6 @selection@
color7 @foreground@
color8 @outline@
color9 @error@
color10 @primary@
color11 @secondary@
color12 @tertiary@
color13 @primary_container@
color14 @muted@
color15 @foreground@

active_border_color @primary@
inactive_border_color @outline_variant@
