-- Generated by Matugen. Do not edit this output directly.
return {
    background = "090b10",
    surface = "212429",
    surface_high = "2c2e34",
    foreground = "ededf5",
    muted = "c2c6d4",
    primary = "abc7ff",
    primary_container = "3972c8",
    on_primary_container = "ffffff",
    secondary = "b4c7ee",
    tertiary = "ffb877",
    outline = "969ba7",
    outline_variant = "686c78",
    shadow = "000000",
}
