-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0c0b08",
    surface = "252420",
    surface_high = "2f2e2b",
    foreground = "f1ede8",
    muted = "cbc6b9",
    primary = "ffffff",
    primary_container = "eae4b8",
    on_primary_container = "3c391a",
    secondary = "cbc7b2",
    tertiary = "ffffff",
    outline = "9e9b8e",
    outline_variant = "6f6d61",
    shadow = "000000",
}
