-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0d0b08",
    surface = "262320",
    surface_high = "312e2b",
    foreground = "f4ece7",
    muted = "d1c5b8",
    primary = "e0c29a",
    primary_container = "816947",
    on_primary_container = "ffffff",
    secondary = "d5c4b1",
    tertiary = "b9c7e0",
    outline = "a4998e",
    outline_variant = "746b60",
    shadow = "000000",
}
