-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0e0a09",
    surface = "272321",
    surface_high = "322d2b",
    foreground = "f5ece9",
    muted = "d5c3bb",
    primary = "edbca4",
    primary_container = "8b6450",
    on_primary_container = "ffffff",
    secondary = "dbc1b6",
    tertiary = "a9cdd0",
    outline = "a89891",
    outline_variant = "786a63",
    shadow = "000000",
}
