-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0a0b0d",
    surface = "222426",
    surface_high = "2d2e30",
    foreground = "eeedf0",
    muted = "c3c7ce",
    primary = "abcaea",
    primary_container = "516f8c",
    on_primary_container = "ffffff",
    secondary = "bcc8d6",
    tertiary = "eabf88",
    outline = "979ba2",
    outline_variant = "686d73",
    shadow = "000000",
}
