-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0c0b0a",
    surface = "252323",
    surface_high = "302e2d",
    foreground = "f2eceb",
    muted = "d2c3c0",
    primary = "f9e4df",
    primary_container = "dcc8c3",
    on_primary_container = "322623",
    secondary = "cfc4c1",
    tertiary = "e2eae8",
    outline = "a59895",
    outline_variant = "756a67",
    shadow = "000000",
}
