-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0b0b0c",
    surface = "242424",
    surface_high = "2e2e2f",
    foreground = "f0edee",
    muted = "c5c6cb",
    primary = "bec7d4",
    primary_container = "646d78",
    on_primary_container = "ffffff",
    secondary = "c4c6cc",
    tertiary = "ddc1b1",
    outline = "999ba0",
    outline_variant = "6a6d71",
    shadow = "000000",
}
