-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0d0b09",
    surface = "262321",
    surface_high = "312e2c",
    foreground = "f3ece9",
    muted = "d1c4ba",
    primary = "dec1a9",
    primary_container = "a58c75",
    on_primary_container = "000000",
    secondary = "d3c4b8",
    tertiary = "b8c9d3",
    outline = "a59990",
    outline_variant = "756b62",
    shadow = "000000",
}
