-- Generated by Matugen. Do not edit this output directly.
return {
    background = "100908",
    surface = "2a2220",
    surface_high = "352c2b",
    foreground = "fbeae8",
    muted = "dac1bd",
    primary = "ffb4a9",
    primary_container = "a85448",
    on_primary_container = "ffffff",
    secondary = "f1b9b1",
    tertiary = "9ad0d5",
    outline = "ad9692",
    outline_variant = "7c6865",
    shadow = "000000",
}
