-- Generated by Matugen. Do not edit this output directly.
return {
    background = "130807",
    surface = "2e201f",
    surface_high = "392b29",
    foreground = "ffe9e6",
    muted = "e0bfbc",
    primary = "ffb3ac",
    primary_container = "bf413b",
    on_primary_container = "ffffff",
    secondary = "ffb3ac",
    tertiary = "85d2e0",
    outline = "b29491",
    outline_variant = "816664",
    shadow = "000000",
}
