-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0a0b0f",
    surface = "222328",
    surface_high = "2d2e32",
    foreground = "eeedf3",
    muted = "c4c6d1",
    primary = "b0c6ff",
    primary_container = "516ba7",
    on_primary_container = "ffffff",
    secondary = "bdc6e3",
    tertiary = "fcb976",
    outline = "989aa5",
    outline_variant = "6a6c76",
    shadow = "000000",
}
