-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0d0b09",
    surface = "262321",
    surface_high = "302e2b",
    foreground = "f3ece8",
    muted = "d1c4b9",
    primary = "ddc2a4",
    primary_container = "bca386",
    on_primary_container = "000000",
    secondary = "d3c4b5",
    tertiary = "bbc7d9",
    outline = "a4998f",
    outline_variant = "746b61",
    shadow = "000000",
}
