-- Generated by Matugen. Do not edit this output directly.
return {
    background = "090b0b",
    surface = "222423",
    surface_high = "2d2f2e",
    foreground = "eeeeec",
    muted = "c0c8c6",
    primary = "a6cfc7",
    primary_container = "4d746d",
    on_primary_container = "ffffff",
    secondary = "bacac6",
    tertiary = "f1baab",
    outline = "959d9a",
    outline_variant = "666e6c",
    shadow = "000000",
}
