-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0a0b0c",
    surface = "232425",
    surface_high = "2e2e30",
    foreground = "efedef",
    muted = "c3c7cd",
    primary = "b4c9e0",
    primary_container = "5b6f84",
    on_primary_container = "ffffff",
    secondary = "c0c7d1",
    tertiary = "e4c198",
    outline = "989ba1",
    outline_variant = "696d72",
    shadow = "000000",
}
