-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0f0a06",
    surface = "29231d",
    surface_high = "342d27",
    foreground = "f8ebe3",
    muted = "d7c3b4",
    primary = "ffb872",
    primary_container = "c3833f",
    on_primary_container = "000000",
    secondary = "e7bf9c",
    tertiary = "7cd3ea",
    outline = "a9988a",
    outline_variant = "796a5d",
    shadow = "000000",
}
