-- Generated by Matugen. Do not edit this output directly.
return {
    background = "080b12",
    surface = "21242b",
    surface_high = "2b2e36",
    foreground = "ecedf8",
    muted = "c2c6d7",
    primary = "afc6ff",
    primary_container = "518dff",
    on_primary_container = "000000",
    secondary = "afc6ff",
    tertiary = "ffb692",
    outline = "969baa",
    outline_variant = "676c7b",
    shadow = "000000",
}
