-- Generated by Matugen. Do not edit this output directly.
return {
    background = "110906",
    surface = "2c221d",
    surface_high = "372c27",
    foreground = "fdeae2",
    muted = "dcc1b5",
    primary = "ffb692",
    primary_container = "db753d",
    on_primary_container = "000000",
    secondary = "f7b99b",
    tertiary = "61d5f2",
    outline = "ae968b",
    outline_variant = "7e685e",
    shadow = "000000",
}
