-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0c0b0a",
    surface = "252323",
    surface_high = "302e2d",
    foreground = "f2edeb",
    muted = "d1c4bd",
    primary = "d1c4bd",
    primary_container = "756b64",
    on_primary_container = "ffffff",
    secondary = "cdc5c1",
    tertiary = "cac6bb",
    outline = "a49993",
    outline_variant = "746b65",
    shadow = "000000",
}
