-- Generated by Matugen. Do not edit this output directly.
return {
    background = "170605",
    surface = "341e1b",
    surface_high = "402825",
    foreground = "ffe9e5",
    muted = "ebbcb4",
    primary = "ffb4a8",
    primary_container = "ff5541",
    on_primary_container = "000000",
    secondary = "ffb4a8",
    tertiary = "acc7ff",
    outline = "bc918a",
    outline_variant = "89635d",
    shadow = "000000",
}
