-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0a0b10",
    surface = "232329",
    surface_high = "2d2e34",
    foreground = "efecf5",
    muted = "c6c5d4",
    primary = "bcc3ff",
    primary_container = "5664c3",
    on_primary_container = "ffffff",
    secondary = "bfc4ef",
    tertiary = "ffb68a",
    outline = "9a9aa8",
    outline_variant = "6b6c79",
    shadow = "000000",
}
