-- Generated by Matugen. Do not edit this output directly.
return {
    background = "140807",
    surface = "30201e",
    surface_high = "3b2a29",
    foreground = "ffe9e7",
    muted = "e3bebb",
    primary = "ffb3ae",
    primary_container = "cd2e32",
    on_primary_container = "ffffff",
    secondary = "ffb3ae",
    tertiary = "89ceff",
    outline = "b59390",
    outline_variant = "846563",
    shadow = "000000",
}
