-- Generated by Matugen. Do not edit this output directly.
return {
    background = "160705",
    surface = "331f1b",
    surface_high = "3e2925",
    foreground = "ffe9e5",
    muted = "e9bcb5",
    primary = "ffb4a8",
    primary_container = "e61407",
    on_primary_container = "ffffff",
    secondary = "ffb4a8",
    tertiary = "b0c6ff",
    outline = "ba918b",
    outline_variant = "88645e",
    shadow = "000000",
}
