-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0f0a05",
    surface = "29231b",
    surface_high = "342d25",
    foreground = "f9ecdf",
    muted = "d6c3af",
    primary = "ffb957",
    primary_container = "c58314",
    on_primary_container = "000000",
    secondary = "e9c08d",
    tertiary = "8cceff",
    outline = "a99886",
    outline_variant = "796a59",
    shadow = "000000",
}
