-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0c0b0b",
    surface = "252324",
    surface_high = "302e2e",
    foreground = "f2eced",
    muted = "d0c3c7",
    primary = "d7c1ca",
    primary_container = "7a6870",
    on_primary_container = "ffffff",
    secondary = "d0c3c7",
    tertiary = "c7c5d3",
    outline = "a3989c",
    outline_variant = "746a6e",
    shadow = "000000",
}
