-- Generated by Matugen. Do not edit this output directly.
return {
    background = "070c0e",
    surface = "202427",
    surface_high = "2a2f31",
    foreground = "eaeef1",
    muted = "bdc8ce",
    primary = "6ed3fb",
    primary_container = "40abd2",
    on_primary_container = "000000",
    secondary = "a8ccdd",
    tertiary = "ffb86f",
    outline = "929da2",
    outline_variant = "646e74",
    shadow = "000000",
}
