-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0e0b06",
    surface = "27231e",
    surface_high = "322e28",
    foreground = "f5ece3",
    muted = "d2c5b4",
    primary = "f2c57a",
    primary_container = "d4aa62",
    on_primary_container = "130a00",
    secondary = "dbc3a0",
    tertiary = "b1ccff",
    outline = "a5998a",
    outline_variant = "756b5d",
    shadow = "000000",
}
