-- Generated by Matugen. Do not edit this output directly.
return {
    background = "110a02",
    surface = "2b2214",
    surface_high = "362d1e",
    foreground = "fcebd5",
    muted = "dbc3a1",
    primary = "ffb4a5",
    primary_container = "ae503d",
    on_primary_container = "ffffff",
    secondary = "ffb4a5",
    tertiary = "efbf6d",
    outline = "ad9878",
    outline_variant = "7c6a4d",
    shadow = "000000",
}
