-- Generated by Matugen. Do not edit this output directly.
return {
    background = "0a0b0f",
    surface = "232328",
    surface_high = "2d2e32",
    foreground = "efedf3",
    muted = "c5c6d1",
    primary = "b3c5ff",
    primary_container = "546aa9",
    on_primary_container = "ffffff",
    secondary = "bec6e3",
    tertiary = "f9ba72",
    outline = "999aa5",
    outline_variant = "6a6c76",
    shadow = "000000",
}
