-- Generated by Matugen. Do not edit this output directly.
return {
    background = "130805",
    surface = "2e211c",
    surface_high = "392b26",
    foreground = "ffe9e2",
    muted = "e0c0b5",
    primary = "ffb59b",
    primary_container = "bd450d",
    on_primary_container = "ffffff",
    secondary = "ffb59b",
    tertiary = "afc6ff",
    outline = "b2958a",
    outline_variant = "81675e",
    shadow = "000000",
}
