-- Generated by Matugen. Do not edit this output directly.
return {
    background = "150709",
    surface = "311f21",
    surface_high = "3c292b",
    foreground = "ffe9e9",
    muted = "e4bdc0",
    primary = "ffb2ba",
    primary_container = "e01853",
    on_primary_container = "ffffff",
    secondary = "ffb2ba",
    tertiary = "73daa6",
    outline = "b69295",
    outline_variant = "856467",
    shadow = "000000",
}
