-- Generated by Matugen. Do not edit this output directly.
return {
    background = "070c0e",
    surface = "202426",
    surface_high = "2a2f31",
    foreground = "ebeef1",
    muted = "bec8cd",
    primary = "73d3f5",
    primary_container = "379fbf",
    on_primary_container = "000000",
    secondary = "aaccda",
    tertiary = "ffb77b",
    outline = "929da2",
    outline_variant = "646e73",
    shadow = "000000",
}
